const PastWorksData = [
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Item Inventory System (Back-end)',
        desc: 'Inventory System with Items, Mounts, Gears, Searching bar',
        footer: 'Back-end',
        image: 'https://cdn-cf-east.streamable.com/image/p5q0w5.jpg?Expires=1787627718564&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=UjVMqoLMHVMLTkt84uH6nFFKFmIonXgkc9MDY5Ji5mokuqBWgUVdZCb1TsopEotBopTbwa7RcwVz~a5~0CQw4TMxpKLDD~wArIABRQIZCvHQ2qaLckDj0n5JmuaeQNjUXvv2MHGPl35OQfomU5~r2a2pXRRLyJ2RjYNIY5Ctyi8obE~i2sY0AJDOFWjiCyLrhGwopL8IuZdJ9hxXX1pgzO-lf9iI~tnuD0~SZ3tTiIhWf5eBJG2cS3~tduPWQ1rpnHMQyfaXQTS5W0dkvEfkZYtqIYMffYNevEnyPAnU7aQW0k95fncdh9ZWFRG1xYtOj7MP10du~SczWaaryO4SAg__',
        url: 'https://streamable.com/p5q0w5',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Optimized Leaderboard System (Full-stack)',
        desc: 'Multiple leaderboards rendering with low Recv. Not causing freeze when refresh. Server-client leaderboard system.',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/2oppph.jpg?Expires=1787627718560&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=RQg6PesJppbrx9AWOjPT1rqfo-mtJm~ptkFQe2xeiE-uCdMMv5L2GNAsC2Au1a5fXpx~5yYSxVEz~UlmbWMcvYv6PXa2GYTRWZHNbOmkIV2~QuCUJt12~pa7ogxgxvRm2diN2DFm1o4tm8GoZBqW~MMv8xdnFAa5ZjwGyP~MoH-T8pd5JldoO0lJifsDaLK82Rglkp5pvsl~8iBVvgU0zwwJYUPTHjxN3CPRTxf-Jf-R-WQshfqc3O1q2ccI1-9IBdeB-kioKRtuAmdlq-pHFVV48uzhAhfSo5iAW-1BWzHKIwmluj~E1ekKlz6Lls7HnLJx-QOya9kyCtpHEamJMw__',
        url: 'https://streamable.com/2oppph',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Code System (Back-end)',
        desc: 'Redeem code for rewards once time',
        footer: 'Back-end',
        image: 'https://cdn-cf-east.streamable.com/image/rbxmrg.jpg?Expires=1787627817763&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=G2vHdx2Y~tJ1cYbtpXWHqStVYuIUrKifXKeoidCkf-XZBdmRJ2QFV5T6F-TJ4kVEGkrIY2crPqPEBby75nSpqlyxve-mNxr7rurYTH4b~v2hOYayu4pL7o4iXu0y1uPRpaWVKMCumKD8u9mOtfJxrU94b6rfd2hwk8DdA7gSiRDrhEKEEgPWYEjMmnIi3RJ-LO8Uc9X0hIdpihQD-oXBW3lkul39~9y9GD6KEZgXpqwwBQhqLNvA4XBttCm68tuYyW7mrn83mx3S8tWOabRrz1J3v5O~oHNctCEoIueFJ0Gj2sbNbv-zAVBSJ8BC2vtgtXpAx1GLLvzGVKyY2MmA5A__',
        url: 'https://streamable.com/rbxmrg',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Advanced Guild System (Full-stack)',
        desc: 'Create your own guild with icon, name, description, limit settings. Guild Request (Accept/Ignore). Guild Invite. Guild Quest (Daily/Weekly). Guild Shop buy with guild coins. Delete Guild. Guild Contributes. Guild Top leaderboards',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/pjske0.jpg?Expires=1787627752084&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=jUlc3NT23-5uoTjFhC3X9elh6VwHpzzhYyURILYYM2fEfME0aU0eeDVmo1dsgsIfL2rJD8LnY5fGD0fgctbfhxl1qAH7f8X8hu1pnYNi2BZOVi~DmHdwDxH06LlTwNoUtjCiSdCjbB6WrPz00c9L6mYbgM-M5LhRJAF~iev3MdOw3jaq8Xdft-jm0CSnPHQph~MU3QfGuosqbBgqytA~mKPNw4F63XjheaPIoi-MEKsl6FJcfexb7ECtT7lvds5BgC4aTZg9QLsJ1~XHI58SyGam2w~xnsVgoeiiptS0D3AD9YFiUuCqEX7qpE3GeRyW9gy7EBhVYiNNR7Vtv08OeA__',
        url: 'https://streamable.com/pjske0',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Item Crafting System (Full-stack)',
        desc: 'Use materials and gold to craft advanced materials.',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/tdz45e-screenshot342727.jpg?Expires=1787629028685&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=Dduu-UV~xaMfwUtMKy-fXkyWbUBCSBJ9EbwSBMWgVOsrh7T48Mp0GGNP8y0IR~tFMtyJfY~JWz3Scg9HFQvM36kdEXm4LX6cGFRzekvDniE4qY5gsGLXEwHCffHfsbFgOzdd6PVpp1E-qFSZqYnD3yfIWwXkKpSbIs0Cp7Qx6~16bqXyi1PVZLLNvTp3IHxPCpAoVXSidku0A67yrzxZky3qzJV~bFqLa9A0Dlus3R1iWihikwEebf6OzKlw4F8n5GFIgkDdKUzSxnN~SJYwk9x0fKsk-8g5Vn3FIPId5eUBac4lbAcF0VUs9MlYxOx7y1Px~jBw4~cdh-S8lN6HdQ__',
        url: 'https://streamable.com/tdz45e',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Settings System (Back-end)',
        desc: 'Settings System with lots of stuffs',
        footer: 'Back-end',
        image: 'https://cdn-cf-east.streamable.com/image/0d0d7r-screenshot850577.jpg?Expires=1787629015355&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=ID4q~1Y6lA8rVv-54lksO7OuhA0UJchwWOcizd7YONzwJ9dlMR-Ci2xXDceIMEM-WeXFt0~86uObgHOfv4mh~O2lXUw5xvi0zJPAbIdEbij4-UOv92eQZIyxy9ayDi-JMn9lJmAFUcD0-lfLYOZ9fJdp27MrAAqiCR2YLveQe~kIH6lAvfIh6knCQ6m3yKbOeKa6REnOeaW2r2Zpq-aEImTL2kFC4Iyo4s5KpG8GUPOJ-wtrh620~0pKU3pIyPlqn66HecQk9f3q0WsI~mnJJIwNDQPnp7frINVh-DQ2klfb2a2aHaH2ghbpBgQUlPP3W4RXuEhHdi8p~p1Cb7FXIw__',
        url: 'https://streamable.com/0d0d7r',
    },
    {
        header: 'ANIME STAR X / FULL-STACK DEVELOPER',
        title: 'Advanced Quest System (Back-end)',
        desc: 'Advanced quest system with daily quests, weekly quests, one time quests (Achievements). Each quest have different difficult and rewards',
        footer: 'Back-end',
        image: 'https://cdn-cf-east.streamable.com/image/jgnkvc-screenshot864799.jpg?Expires=1787629047895&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=YKj5YCsw1ODh~-MpI6Aktg~Jf0k7KAsEDS3I23rAxBIDEKLfz~7fDmuknJIT9~teNKdBi98HuKFj2wgRE3746I8ew3ko49byePEGf5~amJsMJG8WL9t--oZD1qUcQFTeDH5-34uokoBSeq7QINxSbrOYyq3e98quSdsmvCfd~J6a8av8tuTbC-gEkrOQ7vC5DJ8V8nkZbv77eEEpexbouy7cy9XmSunW94pWXAgVzfNj-tvCCAmqml5H7egqZMOTUD9YXmhxogKqLhAIkwsUwBtgAahHfMy7K06TNrv4ZUxYDf~UoprfCmUW8b~qMC4wpjCt2SXsrTykcKHR9IGrJg__',
        url: 'https://streamable.com/jgnkvc',
    },
    {
        header: 'IMMORTAL FISHING / HEAD DEVELOPER',
        title: 'Index System (Full-stack)',
        desc: 'Fish Index system with fish indexs from different islands',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/fp015c_1.jpg?Expires=1787629877025&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=klePkq1tZYm8VVBMcQuLndk-MyvDfbwdwAfz35OWvDZRGYPHbbBQsfv9xL73S5HieEN7LSjggsvkFGaDKNACcfioZXwmKRp9c7pcpeR9oC4LN86fRzDqT9ZcNgFDoyaqIXyUHv-ovto3A9rA~zcOISXMmeB5sWu57dGTaVv66jhGWOg60Vn4GKieVVFjO7bVpCGterg1BQXL2HksQOaY0HWTOZT-uCvOGRJpbnbAo4tBkRIDxdDWOkY-RdfA9-OOGIPRxEdwc~iEGWvU3HUN4weylFt5Bv1eRaecGNhlwEoGjziFhkXyPmhQe8kzriOrYL39wHPkdzsLVLp7oDeo9A__',
        url: 'https://streamable.com/jgnkvc',
    },
    {
        header: 'IMMORTAL FISHING / HEAD DEVELOPER',
        title: 'Fishing System (Full-stack)',
        desc: 'Fishing System with fish skills',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/mf2p1m_1.jpg?Expires=1787629722046&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=NCS5ccUQSR-CT2Lr-vUdxqSNJUgV7tcoOWdvgmNYt9G-IRoshp2-lYYpRcIkxAjYBpBzh9~uuhaXzsqHAtSDbH-od8xsETaTisO2StQhQ6SUYg-I8dXuhyd0V-Fem0eG00UL6-yY5QRUITfzbYexdqMk0~g7dK9b5V~Vdf9F7s6N6Rw84VGv2of4bhj9236~UM8c11gdx6Mk27zeqoylzVb9JgmyaKQj6vLDLYA4fnLE2kcdXcu6ATT0iv3-baRn99q0tk0E8FBoSWLdL5~NJr01lKQDQgk8w~EPXbUHWinz5fnOQ9uLZV7MVmD8zGEhywQm-srtQvR1T8PSfT9zpQ__',
        url: 'https://streamable.com/mf2p1m',
    },
    {
        header: 'IMMORTAL FISHING / HEAD DEVELOPER',
        title: 'Daily Reward System (Full-stack)',
        desc: 'Claim reward daily.',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/ufu608.jpg?Expires=1787629682581&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=E0TOJemcIYYUuCdfXaQVqQwcGUBfRMnZFGdUp5xZNHOa7s6UTJvJGLRZnWhF3QjBZUgyl9fmPY9PWMUXkJ~1wF5JbSGDGOUq~YhYQ06VIxabF5hmfJfW3jttwzP45qvm34zStrSi1LxayTCPPWVd7DHPJzxkAif1jc~tCGHxgI2zZPwuDaD-kAlKcX8ztJ924-QNJbf6AXQlLrZaniEiUITqZFWTR1MWPeT6CINTjSdewZ~dJDs5~~-tApLRz9Y3ZcTpNPqOxcY5lz~fVHY~geIi-ssRywag8VPTxXObfp6~WT31Ew2TZIggYLBnKQr2IveXglx803kW6hSWo4Yiww__',
        url: 'https://streamable.com/ufu608',
    },
    {
        header: 'IMMORTAL FISHING / HEAD DEVELOPER',
        title: 'Trait Reroll System (Full-stack)',
        desc: 'Trait reroll system with bundle products.',
        footer: 'Back-end / Front-end',
        image: 'https://cdn-cf-east.streamable.com/image/k4c1sj.jpg?Expires=1787629907030&Key-Pair-Id=APKAIEYUVEN4EVB2OKEQ&Signature=ZdZBpa6BWDrhejsueBwt4-WeulyhCJrLxpTk1i6XcjakB~LkzZPBoLcfORJkV62Z4Gi26BPB478sG9KCxCKxLXgUXD7UbeziDHTRBToci0aeijc424wIriFedzylnyrEfd2coz7ROi63sOizkihMukFMDWR5FHnHVEcxGlFQL9DecRUa3LMJjQlbS1Ro0vN14KQslt3zGkOXyz-zrqCBIyxKsUXlbSv9cldOYtALrvVZyX~fQUEYGExVZj-hkVmDXzkM9DnNo4bnr4-nIQV~d77g0mHfaMCrLngBjjbNbiwEca0d1NHWN~ZVvoGlBmFgr0p0HbTUnvK9BmU-n4vKSA__',
        url: 'https://streamable.com/k4c1sj',
    },
]